### ISSUE TITLE
Document and list Event states

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1018]
Events are somewhat hacked in right now. 

* Root Node has a `fearured` metadata
  * Should be a Link
* Knowing how to enable posting isn't explained
* Knowing how to enable theme selection, and advance it to next rounds isn't explained
* Knowing how to enable ratings isn't explained
* Changing headline is partially hardcoded
* Countdown clock usage is hardcoded

... Continue this

**Comment by zwrawr** [comment]
* how to enable voting
* how to run magic ( calc coolness)
* how to close voting and show results

**Comment by local-minimum** [comment]
* Knowing what states, and the progression of states that exists
* Knowing how to disable posting after event?
* Knowing how to open game submission
* Knowing how to close compo and jam
* Knowing how to extend compo and jam
* Knowing how to set notification area message
* Knowing how to make news
* Knowing how to set end of voting so countdown count down to that after jam submission hour has ended.

**Comment by sgstair** [comment]
My vote on the way forward with this is to automate more of the stuff that's completely manual and start building an admin dashboard. This is something I'm considering taking up shortly after LD39. 
Unfortunately due to the magnitude of the work remaining to do this, I don't think it's feasible to complete for LD39 at this point.

**Comment by povrazor** [comment]
Yes, for the rest of the week we should be keeping the list of things that break the website to a minimum (unless needed).
