### ISSUE TITLE
Ludum Dare Oscar's

### ISSUE THREAD

**Issue by Cerno-b** [JammerCore/JammerCore#1020]
Some people on the main site complained that this time around the reveal of the results was too lackluster, that it was missing pomp.

So I could totally see having a Twitch live reveal of the results in the future, like the Oscar's. Hosts could be people accomplished in the community, like past LD's winners or people who help out on the code a lot. They would dress up nicely and organize some ceremony, where they reveal the top 3 winners of each category on a live stream. At the end of the ceremony, they would solemnly push the button that publishes everyone's results.

**Comment by povrazor** [comment]
Yeah, an award show would be fun, but it requires lots of prep. Doing something is definitely on the roadmap. I would expect something more along the lines of the EVO game reveal (i.e. two people chatting on a couch), as we don't exactly have the budget for anything more fancy.

**Comment by Cerno-b** [comment]
I think the preparation could be done by each LD's host. It would be quite an honor to host such an event so I bet people would be willing to go above and beyond to make the show a good one, especially with potentially 3000 people who had a stake in the event listening in.

It would be similar to the preLD motivation videos where each maker gives their spin to the video.

The guys and gals over at http://www.adventuregamestudio.co.uk host an event like this and I quite like the idea.

**Comment by Jezzamonn** [comment]
A simple version could be tweeting the winners on each category before announcing everyone's results? That would be fun.

**Comment by Cerno-b** [comment]
@Jezzamonn Hm, I guess, but still much less fun than a celebratory livestream

@povrazor Would you be willing to hand over the ceremonies to other people like I outlined above or do you want to do honours yourself (whatever the format will ultimately be)?

**Comment by local-minimum** [comment]
Here's my suggestion: 

Ask the among the Let's Play-people who should know how to do such thing or be very happy to do it, if they'd be interested in it. If more than one is, ask if they'd could take turns on "our" channel on twitch (if that is even doable, but I guess that's how some channels work) or lottery/take turns a LD each? Anyhow ask the streamers/players if they'd be interested and ask them to suggest a format. Work on our side would be to ensure we can give host the results at a given time so the stream can run as scheduled and hand over the results. So I would suggest planning for a bit more time between closing the game-voting and when the site will show the results so that the stream can be first, exclusive, and on time. I think it could be of interest to larger outlets too as we are a quite large community of our own right that would watch the stream, but I think it would be more fun and right to ask the streamers that actually actively contributes to our jam by playing our games.

**Comment by Cerno-b** [comment]
I know it's pretty late to start organizing something, but I'm still very much interested in having an award show this time. How are you guys feeling about that?

@mikekasprzak Would you allow someone to do it? Maybe Alex Rose would be willing to put something together on short notice? He has live stream experience and people know him from the keynote. I know it will probably be built out of shoestrings since time is running out but I'd rather have a basic live event than none at all. It would allow to collect some feedback and do a proper one next time.

**Comment by mikekasprzak** [comment]
Unfortunately there just isn't time this time around. The holidays tend to
mess with everyone's availability.

I'm on my phone, so I can't recall what I'd said before, but one of the
biggest bottlenecks to doing it right is capturing game footage. There's
little reason to do a live results show without visual aides.

On Dec 27, 2017 12:21, "Cerno_b" <notifications@github.com> wrote:

I know it's pretty late to start organizing something, but I'm still very
much interested in having an award show this time. How are you guys feeling
about that?

@mikekasprzak <https://github.com/mikekasprzak> Would you allow someone to
do it? Maybe Alex Rose would be willing to put something together on short
notice? He has live stream experience and people know him from the keynote.
I know it will probably be built out of shoestrings since time is running
out but I'd rather have a basic live event than none at all. It would allow
to collect some feedback and do a proper one next time.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ludumdare/ludumdare/issues/1020#issuecomment-354146076>,
or mute the thread

**Comment by Cerno-b** [comment]
@mikekasprzak I understand your reasoning although I think having someone respected by the community shout out the winners with a screenshot attached would be quite sufficient for a first attempt. 

Since the keynote speakers decide on the format themselves, I would argue that this may also be possible for the award show. Maybe someone wants to play the winners live during the ceremony, or show some video footage, or just some screenshots, it would be up to the host. 

If there was a cool show during one LD then the next host may want to top that. It would create some healthy variety in the format.

If you don't mind I'll be back next LD bothering you about this early on so maybe next time we can have some sort of show. I would love to see it.

**Comment by mikekasprzak** [comment]
FWIW, some folks put a lot of time in to their keynote videos. Weeks,
sometimes months. It's not a simple matter of respect. There is much
planning and work that goes in to this, even if they lack quality video
capture equipment and professional editing experience.

Making the entirety of the community wait longer for results has to be
worthwhile. Remember, we have many thousands of participants, which means
an opening audience of many thousands. Whatever we do needs to be well
paced, else we're wasting your time.

On Dec 28, 2017 07:37, "Cerno_b" <notifications@github.com> wrote:

@mikekasprzak <https://github.com/mikekasprzak> I understand your reasoning
although I think having someone respected by the community shout out the
winners with a screenshot attached would be quite sufficient for a first
attempt.

Since the keynote speakers decide on the format themselves, I would argue
that this may also be possible for the award show. Maybe someone wants to
play the winners live during the ceremony, or show some video footage, or
just some screenshots, it would be up to the host.

If there was a cool show during one LD then the next host may want to top
that. It would create some healthy variety in the format.

If you don't mind I'll be back next LD bothering you about this early on so
maybe next time we can have some sort of show. I would love to see it.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ludumdare/ludumdare/issues/1020#issuecomment-354282174>,
or mute the thread

**Comment by Cerno-b** [comment]
@mikekasprzak One thing I was wondering though: How can an award show be prepared when the results are only known at the last minute? I mean surely there is a trend in the final days and you can guess who the winner will be, but there simply won't be weeks in order to prepare the material. 

That's why my initial idea was to do something low key where the host doesn't necessarily have to know the results weeks in advance. Maybe a few days before the deadline they could get a list of potential winners as of that moment and they can put together some material.

**Comment by mikekasprzak** [comment]
Well no matter what, on our end we need to provide something to the host.
Be it early access to the data, screenshots, video clips, etc. Who hosts it
doesn't matter.

**Comment by Cerno-b** [comment]
Hmm, so should there be a team of organizers then who put together the material so that the effort does not lie only with one person? 

What format would make sense anyway? Honoring the 10 best games in each category would amount to 80 games to be presented which would require a very long event and may not be feasible. 

10 best overall + 3 best per category would still be 30 games.
