### ISSUE TITLE
Add the "typo bug" exceptions text to rules

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1120]
The typo bug stuff was originally part of the submission page. Apparently never made it in to the rules.

**Comment by Bobsleigh** [comment]
I've composed a guide for bugfixes in the Ludum Dare. I'd like your opinion on it as there are a few things I'm not sure we want to allow or not. I'm aware it may sound a bit intense and I thought the lax rules we had before were enough, but people are really stretching the meaning of every word to justify any change they want to make to their game so I think clear wording is needed.

# Ludum Dare Bugfix rules

As general rule, bugfixes are not allowed. Play testing is an important part of game development and therefore should be done inside the event’s allotted time. It is a good opportunity to invite family, friends and even other developers to play your game and get feedback while in development.

There are a few exceptions to this:

## Ports
Ports to other platforms can be done after the deadline. That said, the sooner you finish your port, the sooner people can play your game, improving your chances of placing in the final results. For best results, provide a Web version of your game, or a Windows version with no dependencies.

This rule concerns ports to other platforms. Changing the controls, performance optimisation and new screen resolution support are not considered ports. You are not allowed to add support for a new control device (controller, joystick...) to an existing platform but you can add controller support for a console port.

## Crashes and fatal bugs
It is allowed to fix crashes and bugs that prevent you from reaching the end of the game. Those bugs generally appear with last minute changes where you thought you didn’t break anything but alas nothing works anymore. We allow this so a small mistake won’t cost you the whole event and showing your hard work to others.

 Examples of such bugs would be:

•	Crash on start-up
•	An unexpected collision prevents the player from reaching the end of a level
•	The last boss is invincible
•	An event doesn’t trigger and prevent the player from completing the game

Excluded from fatal bugs are:

•	The game is hard and some people don’t have the skill to reach the end
•	An unintended way of playing makes the game really easy
•	A skip was found

## Very small bugs
Fixing very small bugs like typos is allowed. Most of the time those are so benign they are not worth arguing about. If you have a doubt, it’s probably not considered a very small bug.

Excluded from very small bugs are:

•	Quality of life changes (UI update, color changes)
•	Game balancing
•	Number tweaking in general
•	AI updates
•	Adding or changing sprites or visual effects
•	Adding text

**Comment by Bobsleigh** [comment]
I kept the "Very small bugs" in there because of the typo rule we have, but I feel like it brings very little. A very small bug will not have a meaningful impact if corrected, and if it does its not a very small bug. I'd lean on removing this section to keep things clear but I'm not sure.

**Comment by Bobsleigh** [comment]
I also wrote guidelines for posting Post-Compo and Post-Jam versions of a game. I see people removing their Jam version and posting V2.0 of their game as their sole link, so I think it can clarify things. Once again I made the wording as clear as possible and went on the strict side.

# Post-Compo or Post-Jam Version
You’re encouraged to take your game above-and-beyond Ludum Dare. Our job is to encourage you to make a game, but after that it’s up to you. 

Keep in mind that the rating and voting process should be done for your Compo or Jam version only. It is the first version they should play. If people then want to play your Post-Event version it’s great! The main goal of the game page is to present the hard work you did during the event to the world, not to get playtesters for an ongoing development. 

To keep everything fair for participants, here are some guidelines on the presentation of your Post-Event version:

•	Leave a log of changes on your page, so new players can see what was changed
•	Put the Event version download link first so that people who don’t read the page still download the right version to vote on
•	Clearly label the download link as Event version and Post-Event version

**Comment by ajayyy** [comment]
One extra thing to add would be variable changes/debug modes. Let's say you upload a debug version of your game instead of your other version. Uploading the one without debug setting might add tons of features, but those features weren't made after the deadline, so they are fine.

Like one time I accidentally left in code to start at level 5 instead of 1. It's just one variable to change, and the levels weren't added after the fact so they are fine.

**Comment by ajayyy** [comment]
> This rule concerns ports to other platforms. Changing the controls, performance optimisation and new screen resolution support are not considered ports

I don't know about the controls part. It is common for some people to add new keyboard layout support. Because in the old rules it said:

> In a sense, this is like “porting” to support more players. We leave this open to interpretation, but generally speaking your game should be identical to the game you submitted.

**Comment by ParkerMc** [comment]
I don't know if this would be the right place but personally I would add something saying that some people use linux (including me) I would add it kind of like this:
>For best results, provide a Web version of your game, or a Windows version with no dependencies.
While most jamers use Windows there are a number of them who use OS's like Linux and Mac.

**Comment by ajayyy** [comment]
I agree with having them, but those are really two contradictory sentences.

**Comment by Bobsleigh** [comment]
@ParkerMc I added 

>  Since other people use macOs and Linux too, the more ports the better!

To convey the idea that other platforms are useful too.

**Comment by ParkerMc** [comment]
Thanks, I'm glad there are better writers than me.

**Comment by Bobsleigh** [comment]
@ajayyy Debug stuff is indeed a good addition: 

> •	Debug values and menus left activated in the released version

**Comment by ajayyy** [comment]
I suggest adding
> or left inactivated

**Comment by Bobsleigh** [comment]
@ajayyy I feel like tweaking the controls falls into the game balancing category. Small stretches of the rules can still happen, like if I coded the fire button on the mouse wheel instead of the left button by accident, but remaping your keyboard controls because you got comments saying they are hard to use sounds like a big change. Since those rules are intended to be a reference and not a law to enforce, I'd keep this part in.

**Comment by ajayyy** [comment]
But making controls work with AZERTY keyboards isn't really game balancing.

**Comment by Bobsleigh** [comment]
@ajayyy debug values left unactivated? Or you mean features?

I agree on the controls port, ill add it to the port section.

**Comment by ajayyy** [comment]
Like a skip to level debug setting, or a hide menu screen, or hide enemies.

**Comment by Bobsleigh** [comment]
@ajayyy you generally want to leave all debug settings unactivated. I feel like I don't understand ehat you mean. What would you change the complete sentence to?

**Comment by povrazor** [comment]
Ah sorry, I edited your original.

# Porting, bugs, and fixes
When the event is over, your game is done. It should not change. The game you submitted at the end should be the same game being rated 3 weeks later.

That said there are exceptions:

## Ports
Ports to other platforms can be done after the deadline. Because the time rate games is only a few weeks, it's highly recommended you finish your ports as soon as possible. For best results, provide a Web version of your game. The easier it is to immediately start playing your game, the better. Alternatively, Windows, macOS, and Linux versions are recommended. If you did one already, try to do the others.

Ports should be as close to the submitted version as possible. Platform specific changes are fine. If the differences between platforms are exotic (e.g. PC to Mobile), then do what suits the platform. That said, still try to provide a game that's as close to the submitted version as possible.

Porting your game is not necessary, but it is encouraged.

---
NOTE: I haven't edited past this point yet.
---

## Crashes and fatal bugs
It is allowed to fix crashes and bugs that prevent you from reaching the end of the game. Those bugs generally appear with last minute changes where you thought you didn’t break anything but alas nothing works anymore. We allow this so a small mistake won’t cost you the whole event and showing your hard work to others.

 Examples of such bugs would be:

•	Crash on start-up
•	An unexpected collision prevents the player from reaching the end of a level
•	The last boss is invincible
•	An event doesn’t trigger and prevent the player from completing the game
•	Debug values and menus left activated in the released version

Excluded from fatal bugs are, among others:

•	The game is hard and some people don’t have the skill to reach the end
•	An unintended way of playing makes the game really easy
•	A skip was found

## Very small bugs
Fixing very small bugs like typos is allowed. Most of the time those are so benign they are not worth arguing about. If you have a doubt, it’s probably not considered a very small bug.

Excluded from very small bugs are, among others:

•	Quality of life changes (UI update, color changes)
•	Game balancing
•	Number tweaking in general
•	AI updates
•	Adding or changing sprites or visual effects
•	Adding text

If you keep working on your game after the event, you can publish your changes as a Post-Event version (see the guidelines further down).

**Comment by Jezzamonn** [comment]
Oh... I definitely broke that rule in that case. Good idea to clarify then! I was under the impression that bug fixes were in general ok. I guess I better revert my change O_O

**Comment by povrazor** [comment]
Well a lot of people made that mistake. ;)

**Comment by povrazor** [comment]
Okay I've finished me edit above. It's a modified version of what Bobsleigh wrote, so a huge thanks to Bob for for figuring this out.

Put yourself in the shoes of a first time participant of Ludum Dare. You finished your game, uploaded it, and you want to know what happens next. What have or haven't we covered that confuses you? Does it have too much rambling? Tear it apart!

**Comment by timeracers** [comment]
@Bobsleigh Why exclude screen resolutions? If you have a large game resolution then some people won't be able to play it, just like not having a version for linux. Changing the screen resolution doesn't change the experience people have unless the prior resolution was super small.

**Comment by Bobsleigh** [comment]
@timeracers I felt like tuning the screen resolution was a pretty big change, but I see what you mean. Pov rightly skipped over that section in the V2, which is the one that should now be discussed.

@povrazor I'm happy with the version you posted. Everything important looks covered, and in a much LudumDarier way than my draft.

**Comment by ajayyy** [comment]
You are right, it's not included at all, that is good. I also like how he included:
> If the differences between platforms are more extreme (e.g. PC to Mobile), then do what suits the platform. But again, try to keep it as close to the submitted version as possible.

**Comment by timeracers** [comment]
I just realized that a iOS port would require changing screen resolution in most cases.

**Comment by mikekasprzak** [comment]
Moved here https://github.com/LudumDare/ludumdare.com/issues/3
