### ISSUE TITLE
Confused by total ratings

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1131]
![totarat](https://user-images.githubusercontent.com/1570313/28806724-97097b5e-763f-11e7-8e81-094c6e8c8d2c.jpg)

We had a user confused by the number of ratings (i.e. 1). They assumed they got low ratings.

The section already says "Total" at the top. Is there a simple change that can be made here that will make it more obvious we're talking about totals, not actual ratings?

**Comment by matthewvroman** [comment]
Quick fix might be to add the word  'vote' after each number. 

- Overall: 1 vote
-Fun:  1 vote
-Innovation: 2 votes
etc.

While redundant, it clearly calls out what that number is and doesn't rely on the user reading the small subheader or footer.

Alternatively, you could consider replacing 'Total Ratings' with 'Total Votes'. Seeing 'Ratings' in big bold letters might be what makes users immediately associate the numbers below a score and not a vote count.

**Comment by povrazor** [comment]
Adding `vote` on the end is a nice solution.

**Comment by karai17** [comment]
A somewhat unrelated issue I have with voting/rating is the ambiguity around how many votes in a category you actually need to qualify. In previous LDs, the accepted number was 17. Last LD I was ranked even though we had less than 17 in some categories. Is there a specific purpose to the ambiguity? I think it would be much more helpful for people to understand being told "around" 20. Is that below 20? above?

**Comment by zwrawr** [comment]
If you get 20 votes you will definatly get ranked.

However we try to rank as many people as possible. We lower the minimum
vote as far as possible, stopping just before a game with a low number(eg.
15) of votes gets ranked high (eg. Top 10 in a category).

Often this means that games get cut off a bot lower than 20 e.g. the 17
votes you talked about

**Comment by karai17** [comment]
I know that the more you judge the more you get judged, but there is no purpose to ambiguity. Just give us a set number we can strive for so we know we've at least hit the minimum instead of being forced to over-achieve just to feel safe.

**Comment by zwrawr** [comment]
As i said, aim for 20. Thats safe point.




On 4 Aug 2017 19:28, "Landon Manning" <notifications@github.com> wrote:

I know that the more you judge the more you get judged, but there is no
purpose to ambiguity. Just give us a set number we can strive for so we
know we've at least hit the minimum instead of being forced to over-achieve
just to feel safe.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ludumdare/ludumdare/issues/1131#issuecomment-320321198>,
or mute the thread

**Comment by karai17** [comment]
You're missing the point. The point is that the actual number is ambiguous. That makes no sense! If you shoudl "aim for 20" then just tell peopel that they need a minimum of 20. If the number is not 20, tell them the real number!

**Comment by povrazor** [comment]
20 is the magic number. It's what we tune for. Rather than specifically say "you need 15" one event, and "17.5" another, it's a round simple number that gives us the headroom to tweak the algorithm and make improvements.

Funny thing, we don't have the luxury to make people read. It's simpler to say "do 20" without going in to detail. Once we can see that 20 is working, we can tune the values accordingly for the best spread.

**Comment by karai17** [comment]
What is there to tune? I can understand reading analytical data to see what
the average number of votes are and tryign to bring more people into the
threashold, but if there is an actual algorithm in place to determine the
minimum, that seems like over engineering to me. We have 38 previous sets
of data to determine what a good minimum should be, why can't we just make
it an integer instead of an equation?


---
Landon Manning
lmanning17@gmail.com

**Comment by zwrawr** [comment]
If you have 20 votes on your game then your guaranteed to get ranked. 
There is no ambiguity in that.

But we want to rank as many people as possible so if we can squeeze a few hundred more games in without changing the winners then we do.

**Comment by povrazor** [comment]
Ratings don't actually matter to the vast majority of participants. They matter if you're in the top 10, or top 100, but that's usually less than 10% of everyone that took part. What matters to the majority is feedback. 

We introduced a new system that prioritizes users that leave ratings and good feedback ahead of those that just rate. We don't know if it actually works. Of course it functions, but the intent is to help grow the amount of quality feedback inside the system, while also providing enough data to score the games.

Despite suggesting a 20 rating minimum for many years, the true minimums were far lower. When it's that low, a game that meets the exact minimum number of votes, and finds the perfect combination of players can win the event. There are far better algorithms than straight averages.

Ludum Dare is an inclusive event. It's also constantly changing. We want everyone that takes part to feel like they achieved something. So by not revealing the exact target, it gives us the flexibility to to give more people that sense of accomplishment. We can test the results. If the winner data goes uncorrupted by letting games below the threshold through, then we've made a few people's experience that much better.

**Comment by karai17** [comment]
I can understand that. Then instead of using ambiguous wording (*around* 20), it might be wise to just say 20 and the internally allow it to be a little less. People like solid numbers.

As for "mattering", I think that is very subjective. While I don't expect myself to get into the top 10 when competing against thousands of people, I am very excited to see if I've gotten into the top 100, or just gotten a better rank than my previous entry. KNowing that I got 363rd instead of 689th matters a lot to me since it shows that I am improving in that particular category.

**Comment by povrazor** [comment]
We do.

![minimum](https://user-images.githubusercontent.com/1570313/28987830-f2e427e6-793a-11e7-866c-0dbc2be0126f.png)

That little alert only goes away if you have 20+ ratings.

What's missing is that on the homepage, alerting users that hey, you need more votes.

Also we can't actually guarantee that rating 20 will actually work. If you game is for an exotic system (VR, board games), you're not necessarily going to find 20 people that are able (or willing) to play your game.

**Comment by povrazor** [comment]
> KNowing that I got 363rd instead of 689th matters a lot to me since it shows that I am improving in that particular category.
We're literally talking 30-50 games here and there. In practice you're not losing more than 3-4 places.

**Comment by karai17** [comment]
I'm not really worried about going up or down a couple notches, just the genereal "you improved your ranking by 20%" is important for me.

**Comment by povrazor** [comment]
Yep, and that shouldn't be a problem. This is nothing new. We've always done this. Just on the current software I can tell you exactly how many games entered the top 100 in a category thanks to lowering the threshold. Some categories you don't even see 1.

**Comment by karai17** [comment]
I know it's nothing new, I am simply bringing it up because it's always urked me. And considering we're using a whole new platform these days, now's as good a time as any to suggest changes.

**Comment by povrazor** [comment]
Fair enough. Back in the day I would only ever check the top 3 (by hand). Now that it's part of the scoring script, I can reject thresholds for damage at higher depths.

**Comment by karai17** [comment]
I am aware that there have been times where someone had cheated and you disqualified them, I think they were very few times. How often do you find people that look like they are trying to game the system? For instance, giving tonnes of people 1 star ranks to try and boost their own rank and get more feedback since they have a lot of ranging done, or someone obviously using multiple accounts to give themselves a higher score, etc. Have you ever seen someone attempt a raid where they have a bunch of friends go in and 1 star obviously good games and then 5 star a single game? This sort of data is interesting to me as I find it bizarre that someone would try so hard to cheat and win in a competition that has no prizes :P

**Comment by povrazor** [comment]
We've disqualified once. Never because of cheating, but because it was a virus.

**Comment by karai17** [comment]
Oh! I was not aware of that minor detail. Kudos on finding it before it did too much damage.

**Comment by povrazor** [comment]
Yeah when we catch someone abusing the system, we have a chat over e-mail, and I reset their rating count. Or move them to the Jam depending on what's "cheating" about it.
