### ISSUE TITLE
Allow joining more than one game

### ISSUE THREAD

**Issue by winniehell** [JammerCore/JammerCore#1422]
Especially for people making assets (music / graphics) or who want to take part in compo and jam with a different game, it would be nice to be able to join multiple games.

**Comment by winniehell** [comment]
Correction: It is possible to join multiple games. It is just not possible to start a new game when you are already part of one.

**Comment by local-minimum** [comment]
I'm guessing that what happen when you click the my game button and all other things like towards what game your votes count need to be taken into account too.

**Comment by winniehell** [comment]
Yes, "My Game" only links to one of them and "New (blog post)" only allows creating blog posts for one of them.

**Comment by winniehell** [comment]
For Ludum Dare 40, I was part of two games in case that helps debugging.

**Comment by mikekasprzak** [comment]
Yeah, multiple game support isn't there yet. Behind the scenes it works,
but the user experience is vague and unclear.

How it's working right now: My Game and New Post points to the last game
from the active session that was edited. If you refresh, it may change
(caches pending). Long term this isn't practical, but it helped us work
around an issue for folks that joined before realizing they should be part
of a team.

How it should work: that depends.

For most users, the current assumption mode is fine. In general we do still
need fine-toothed control over which game we're posting to (outside event
weekends).

For a hand full of others though (sound designers, floaters at jam sites,
etc), they almost need a way to say "hey I'm doing multiple games".

We could always display all games from the current event you're associated
with, except when it's just one. That just means the next request will be
"deleting the bad game", for those users with 2 games accidentally.
Ultimately this is fine. But because of potential orphaned
posts/history/metadata/links/references, it needs to be handled with care.
