### ISSUE TITLE
Hide "Whoa! What's going on here?" permanently after it's been dismissed

### ISSUE THREAD

**Issue by Jezzamonn** [JammerCore/JammerCore#1488]
The X seems to indicate that after you close it, it'll go away, but whenever you reload the page or open in a different window it comes back

If #1487 is done then there should be a place to access all of this still.

**Comment by povrazor** [comment]
It shows up when you are not logged in. It's too big IMO (and not pretty enough). I needed something ASAP and that fit the bill.

**Comment by zwrawr** [comment]
We need to set a cookie saying you've dismissed it. Then it won't reopen, even if your not logged in

**Comment by povrazor** [comment]
If login persistence was fixed 100% it would be less of an issue. ;)

**Comment by ttencate** [comment]
On #1142 you were claiming that it's a good idea to log people out after two days, or a week, of inactivity. Wouldn't this mean they get Whoa'd whenever that happens (which will be at least once every 4 months, probably more often)?

But maybe that comment was tongue-in-cheek. Anyway, I think @zwrawr's suggestion is the way to go. Or even use local storage, because this bit of data doesn't need to travel to the server.

**Comment by mikekasprzak** [comment]
I think the "Whoa" is ugly, and when it's something more interesting,
that'll help.

One of the worst things on the internet is when you see an ad for the same
thing every time. Though this isn't an ad, it's similarly annoying.

**Comment by ttencate** [comment]
An extremely simple stopgap to make this less jarring: remove the header "Whoa! What's going on here?", and make "We're making video games!" into a header instead.

Because when I arrive on an unknown website, "Whoa" is not usually my first reaction -- and if it is, it's usually in a bad way ;) Or if the site is saying "Whoa" because I'm visiting it -- that doesn't come across as very welcoming either :)
