### ISSUE TITLE
Let media users signup for event

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1520]
I think it would be nice if those who consider themselves media could sign up as covering an event. This would be a different type of status compared to participating in the event.

We could let media people vote on games. These votes would not be taken into account when ranking games like we do at the end, because this should only be for participants. But we could have a separate media-category (if we have enough grades). The number of grades needs to be lower than normal though. Maybe we don't even show the grade, just the rank to allow for super few grades. My suggestion would be to use the "one angry voter strategy" and let all games, even if 0 votes, be included. It is sensitive to cheaters but it wouldn't hurt trying. A media voter maybe needs to vote on at least 10 different games to be included in the stats. As an example.

One reason to allow this would be that media-people would have access to features such as filtering away games they've already voted on (when that is implemented).

Another would be that the list of what you have graded might be a nice tool for them. Both in remembering what has been played, but also how good a game was.

**Comment by mikekasprzak** [comment]
I got serious backlash when I suggested this before.

Instead what's going to happen is there's going to be a separate category for non-participants.

**Comment by local-minimum** [comment]
Alright, that pretty much would have the same effect though. Good.

**Comment by zwrawr** [comment]
So i have an idea very similar to pov's, but what i will say is that we should keep this open for at least a couple of LD's and get lots of feedback on it before we implement it. Because being rated by your peers is one of key points of Ludum Dare, we should be careful when making changes around it.

I would propose adding two new categories.  
**Public** and **Alumni**. The first being open to anyone with an account who hasn't participated in any event and the second being open to anyone who has participated in a previous event but not the current one.

Adding these as separate categories means that the value and meaning of the existing categories don't change. Whilst still encouraging more people to engage with Ludum Dare when there not participating.

**Comment by mikekasprzak** [comment]
The only concern with separating them is the number of "alumni" that rate games in events they didn't participate in are few and far between. Nowhere near enough for a result.

That said, the plan isn't necessarily for a result anyway. Once an LD event has passed, you're going to want to be able to leave a rating on games as a general viewer of the website. That's what this is.

**Comment by local-minimum** [comment]
Fair enough. We could let people rate though not do anything with it though in case they want to keep track of their views on the games. We need to be clear though whichever way.
