### ISSUE TITLE
No way to gain permission to post between events

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#1545]
As far as i can tell the `join event` button is what gives user the right to post, if you create an account outside of an event you have no way of making a post.

**Comment by mikekasprzak** [comment]
The issue is where to put the posts. All posts right now go under a game
created for an event. This means that if you have 2 games, each game can
re-use existing names for posts, since each is a unique pool.

One option is to put them directly under the user themselves, a sort of
personal diary. The problem is then what happens to games that don't belong
to an event? Where do they go? Do they share the same namespace (i.e. both
go under the user)?

Maybe that fine making games and posts share a namespace, at least when
only a single person is involved.

Alternatively games go under /games or /items or such... Though I can't
remember if that is virtual or not. That way, an eventless game doesn't
belong to a single team member. That means there's a limited/shared pool of
game names for everyone, but maybe that's fine. Then once that game exists,
it too can be the target of posts.

That still means you can't post without a game. So again, being able to
Target yourself would be useful.

Ultimately, some means of selecting the target for posts is needed. Not to
mention it should be seamless and automatic, for users that don't care.
That, and having some way to move a post to a new parent (game or self) is
needed.

**Comment by local-minimum** [comment]
What if games must go under an event, then users can post under the user for general stuff. If we want to let people create games outside events, then we could have ever running events. If it is allowed to swap parents too one could imagine creating a game for the never ending event `prototyping` and if you compete the game you could move it to `releases`.  Maybe even you need apply to get into some events. Just throwing ideas around.
