### ISSUE TITLE
Code Documentation/Comments

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#1586]
There are now hundreds of files in 'src/com', remembering what they do and what props they expect is a problem. We should start documenting that.

I suggest using [documentation.js](https://github.com/documentationjs/documentation). It uses the JSDoc format (similar to javadoc format). Preact itself uses this documentation standard ([see](https://github.com/developit/preact/blob/master/src/util.js)).

Every component should have documentation that explain what it is and what props it expects. something like this.
```js
/**
 *  An example Component for examples
 */
export default class ExampleComponent extends Component {

    /**
    * @param props expects {title, subtitle, desc}
    * title and subtitle must be strings
    * desc can be any html
    */
    render(props) {
    ...
    }
}
```

document.js can then be used to turn this into markdown or html. But even is we don't generate markdown, the comments them selves are very useful

**Comment by mikekasprzak** [comment]
There was an early documentation generator script here:

https://github.com/ludumdare/ludumdare/blob/master/scripts/docs/javascript/make.sh

It uses JSDoc (?). It's probably totally wrong now though.

**Comment by local-minimum** [comment]
Half of this is what proptypes is for. Doesn't say what variables mean but what type, default value and will complain when stuff doesn't comply with expectations.

**Comment by mikekasprzak** [comment]
I'm tempted to write my own documentor, since I've been struggling to find something that's C/C++/PHP friendly, and not stuck in the 90's (i.e. Markdown makes good docs, using markdown in code would be nice, and if you browse GitHub anyway it's sensible to place docs alongside code).

Design in still early, but I've opened this project for feedback.

https://github.com/mikekasprzak/reldoc
