### ISSUE TITLE
Impose restrictions on submission

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1626]
Now that the website is stable enough for submissions, we should impose restrictions on submissions:

* Time - Only allow Compo to be selected until 2 hours after compo deadline, or if published before then (for all those people that click the wrong event and contact me after)
* Team Size - if >1, disallow the Compo

**Comment by local-minimum** [comment]
I briefly researched this and while it isn't hard, the structure of the code makes it very impractical since getting the authors list is part of `<ContentSimple />`  while the logic behind what is allowed need to go in the `<ContentItem />`.

Which again makes me wish we used the Container pattern https://medium.com/@learnreact/container-components-c0e67432e005

And https://redux.js.org/ (which does have a selling-point that it is tiny 😉 )

Reworking the structure of the code base would be a huge undertaking, but I think it would make it more accessible to contributions if organized in a standard and very predictable way and I think we would work much faster adding features to it too.

**Comment by mikekasprzak** [comment]
A change I've been making to a bunch of code that greatly simplifies things is taking code that looks like this.

```html
<ContentSimple node={node} user={user} featured={featured} path={path} />
```

And changing it in to this.

```html
<ContentSimple {...props} />
```

**Comment by local-minimum** [comment]
Can we close this now?
