### ISSUE TITLE
What happened to LD42 & LD39?

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1904]
![Screenshot_20200921-175239__01](https://user-images.githubusercontent.com/8041100/93790752-adf0ea00-fc33-11ea-9f57-610f695a7e95.jpg)
For some reason they don't list among previous themes

**Comment by zwrawr** [comment]
https://ldjam.com/events/ludum-dare/49/theme/idea

refreshing the page can cause the events displayed to change. It appears to be randomly picking events but I don't think it's intentional

![Screenshot from 2021-10-01 21-52-35](https://user-images.githubusercontent.com/18352787/135685191-d331f9e9-aee9-4b2b-82b0-9c458563adb3.png)
![Screenshot from 2021-10-01 21-54-20](https://user-images.githubusercontent.com/18352787/135685192-a489caf0-e450-4f17-85a9-503d0c333c7e.png)
![Screenshot from 2021-10-01 21-54-36](https://user-images.githubusercontent.com/18352787/135685193-e97452c8-a6b5-4b51-9140-684898ae6b4c.png)

The issue is probably in this line. The sort function is incorrectly used.
https://github.com/ludumdare/ludumdare/blob/7bcda4cf2a166696e1507f2dcc583390d8e33eae/src/com/content-event/event-idea.js#L58

The correct usage would be this.
```js
.sort((a,b) => (new Date(b.meta['event-start']) - new Date(a.meta['event-start'])))
```
