### ISSUE TITLE
"Where should I upload my game, source code?"

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#469]
One of the things new people often ask is where they should upload their game (and source code).

The easy answer is Itch and Github, but I want a better answer then that.

I would like a nice list I can copy+paste somewhere. I am, of course, a little busy right now (hehe), so I'm looking for volunteers to help make a list.

**1.** Where should people host their games?
**2.** I need someone(s) to make a master list (and this looks like a good place to do it)
**3.** I want the list to be refined. Yes, more options are good, but too many are confusing. Think about what it's like to have participated in Ludum Dare for the first time. You just spent 48 hours crunching together a game. You're tired, you're ready to submit, and oh sh*t, you didn't read the part that said you had to host your files yourself. Oops!

That is the task. I leave it up to you, whomever decides to come here and help out. :smile:

Thanks!

**Comment by miriti** [comment]
I would suggest considering github.io as a nice free hosting for static files

**Comment by povrazor** [comment]
I'm going to leave the discussion to all of you, but I will say that github.io does require GIT and Source Control knowledge. Not everyone that's new to Ludum Dare knows source control.

**Comment by crabcrabcam** [comment]
You can host your files many places: 
The best place for source code is GitHub, but that's probably not the best place for the binaries.
For the binaries go with itch.io because it's easy to use, and you can embed the Unity webGL or UnityWebplayer file you exported if you used that. It also has a really good tool for helping you get mentioned. 

Github is what I'd suggest for source because you can upload from the browser, and if you're done then you don't need to know Git. Itch could also host the source as a separate ZIP file. 

I started writing this as a guide and ended with suggestions so that's why it looks and reads weird :P

**Comment by avivbeeri** [comment]
Itch is a great place for games too!

**Comment by zwrawr** [comment]
You also have Drive/Dropbox ect.

**Comment by crabcrabcam** [comment]
I'd say no.1 is itch. Number 2 would probably be GameJolt for me. Then your own site. If anyone knows any others that would be good. @zwrawr good point with Drive/dropbox. 2 files linked. One with code and one with game. Obviously they don't need source code if they're doing Jam, but it's probably best to put it there because many start with Comp like me :)

**Comment by arzi42** [comment]
I wrote a blog post on this for the ludumdare.com site: 
http://ludumdare.com/compo/2016/12/09/hosting-games/

**Comment by crabcrabcam** [comment]
@arzi42 seems like a good one. Will need tweaking when we're back over to ludumdare.com but that's not hard. I'd say that's pretty comprehensive to be honest. Nice work :)

**Comment by lparkermg** [comment]
I've sometimes put mine up on Kongregate and I have (in the past) self hosted my own files, but I usually use Itch.io currently.

**Comment by crabcrabcam** [comment]
@lparkermg How hard is it to host on Kongregate? And do they do downloads / UnityWebPlayer or is it only WebGL or flash over there?

**Comment by arzi42** [comment]
I added GameJolt and GitHub Pages to the list. Kongregate is another one, any comments one that (I have never used it for hosting).

**Comment by lastebil** [comment]
I would reccomend _not_ dropbox, drive, or any of those "free" hosting things:  first of all, a popular game may exceed the limits, causing the need to go get 'another' - second, many of us/many companies block those sites for security reasons.

Itch is fine, and suitable for the task; github / gitlab / are also.  I suppose Bitbucket as well, as some folks will put up with the gawdafful JIRA crap; I host my own gitlab because "opinionated truck is opinionated."

I realize that a lot of people will feel that hosting the files on their own server is out of the question, but as someone who's done that for 20+ years, there are advantages that I see:
1. I get logs saying how many, when, and _what platform._
2. If the game, itself, is hosted there (html/javascript/etc) then I can see how many times folks return.
3. I can use that data _within the game_ if I like.
4. I have control over the system, and can take it down if there are issues _without impacting others._
- I actually could go on about this... but yeah, in MY opinion, hosting yourself is absolutely an option.

Maybe I will look at a "host yourself" cheap option for future LD things for folks to use. I've got servers, and it might be something folks would be interested in.

**Comment by crabcrabcam** [comment]
@lastebil Hosting yourself is obviously the best, but if you can do that you'll do it anyway. This is for first time LDers who are less likely to know how to do all that and a simple uploader is what they want. But yeah, I agree. If you can use your own website, then do. But Itch does give more publicity because unless you've been doing the website thing for a while it's not going to come up on google for a while. 

The idea for a "Host yourself" for LD is a good one, but it depends on how easy it would be to maintain and whether enough people would want it over the other alternatives such as Itch or GameJolt.

**Comment by rblopes** [comment]
What you guys think about [Neocities](https://neocities.org/)? It that a good option?

**Comment by lastebil** [comment]
I'm just saying we shoudln't leave it out of the list - _even for firsttimers._  First timers aren't simple - and we shoudln't treat them as if they were.

But perhaps a "bundle" of "self-hosting" stuff would help - or an uploader tool you refer to - and I'll think about that after the jam.  Or a platform.  Because "48 hours, tired" _is_ a thing.

It should absolutely be at the _bottom_ of the list (:

@rblopes I haven't seen that, but I'll consider testing it - if for no other reason than to see if a 'tool' or 'pack' is better for the 'if you want to self-host' option I'm suggesting (at the BOTTOM of the list (:  )

**Comment by lparkermg** [comment]
@crabcrabcam I haven't put anything up on there for a while, though it's easy enough to upload a game. I think it's all webGL now (and maybe flash).

**Comment by dkniffin** [comment]
@arzi42 I think that blog post is great! Should we also add some details about source code hosting options? Github, GitLab, Bitbucket, etc.

**Comment by arzi42** [comment]
@dkniffin Thanks!

I can add the source code options too. What's the difference between GitHub and GitLab?

**Comment by dkniffin** [comment]
I actually haven't used it, but my understanding is: it's got more features, but it's newer and less popular. Anybody else, feel free to chime in.

**Comment by crabcrabcam** [comment]
@lastebil Can you come in on GitLab? You said you'd used it.

**Comment by lastebil** [comment]
Sorry @crabcrabcam and everyone - I'm preparing for LD (making sure things are ready (:  )

Yes, I have used gitlab in both private and office settings; it's very much like github, except you can self-host it.  They also offer a non-self-hosted version.

It is less popular, but my experience is that it is just as usable as github; I do prefer it for _teams._  I haven't used it's new continuous integration features - and I _really_ doubt that's something that would be needed for most LD projects - but maybe it is for some jam folks.  I actually have been using it for myself over github in the past year and a half.

There are some free hosting gitlab places other than gitlab.com - but according to https://about.gitlab.com/gitlab-com/ it's free forever and unlimited.

I'd say, in my own opinion, that gitlab would be something I'd want for a jam team (1+ people) and for single users, either github, gitlab, or bitbucket.

- Did some quick looking for other free hosters, and hit some criticism of those 3 from folks who adhere to certain software licensing things (I am not one of those folks, but I acknowledge that it's something one might want to consider) and came across https://notabug.org/ which is a gogs type repository.  No experience with it, or with gogs, have been happy with gitlab (:

@arzi42 that post is excellent, and yes, I'd say maybe add a repo hosting part to it.

**Comment by arzi42** [comment]
@lastebil Thanks! I added the source hosting to the post.

**Comment by TA418** [comment]
I actually found this useful. I will be using GitHub for the source code (my repo already exists) but wasnt sure where to put the game! Thanks a lot!

**Comment by rblopes** [comment]
Decided to check a little more on Neocities and tried it myself.

It is OK if someone wants to host a simple, small, Web based game. The free subscription gives 100MB storage w/ 50GB bandwidth, upgradable if one's willing to become a supporter, paying a few bucks per month.

The downside, though, is that the free subscription is [restricted to hosting a few file types][0], an info that I couldn't find rightaway before subscribing. It's no surprise at all that they restrict video and audio formats to avoid problems like copyright issues.

So, if those restrictions are not much a problem it's OK to post a game there, I think. Otherwise, better look somewhere else for alternatives or just stick to the ones listed here or in @arzi42's blog post.

[0]: https://neocities.org/site_files/allowed_types

**Comment by arzi42** [comment]
Ok, I removed Neocities from the list as it sounds too limited to be much of use in terms of Ludum Dare.

**Comment by rblopes** [comment]
@arzi42, nice, thank you.

**Comment by zwrawr** [comment]
Take look at this [gist](https://gist.github.com/zwrawr/d2ceb40c83d582192cdd80b0268a91cb). Its in markdown so it can just be copied to ldjam.com. 

I made a gist of based of @arzi42 post, with significant changes.
* I reworded a lot of it so that i sounds more like guide from ludumdare rather than a post by a user. 
* I changed the order and split up hosting and submitting
* I added a placehoder section for a "how to submit a game on ldjam.com"
* I removed the "which platform" section, because its probably too late to change your platform if your reading a how to submit guide.

**Comment by povrazor** [comment]
This is great. I'll give it a quick read to see if anything jumps out at me.

**Comment by povrazor** [comment]
The "Game Sites" section is actually a sticky subject, and should be made more impartial.

* Please add Newgrounds (long time supporter of LD) and Kongregate
* Criticism of Advertising should be removed (GameJolt)
* Most sites have tagging so "list of LD games" shouldn't be a factor
* Itch being first is fine, but its description can be improved to make it more impartial (remove 'common solution, even though it is true)

In the DIY section, I'm a bit reluctant to suggest loomhost, partially because it's the only one, and the other part because I've never heard of them. This guide will be interpreted as us endorsing them, and for the most part we have seen folks use every other mentioned service successfully.

If it exists, I would rather suggest linking an off-site directory of free web hosts, than include loomhost. Again, it's just not something we're qualified to judge.

**Comment by zwrawr** [comment]
* Added Kongregate
* Added Newgrounds 
* Removed criticism of advertising
* Removed reference to tagging 
* Removed 'common solution' for Itch.IO
* Added more "Getting started Guides" if available, otherwise added link to upload point
* Removed reference to LoomHost

There are some lists of free web hosting companies but, it's probably easier to google "free web host" than to use them. Here is one http://www.free-webhosts.com/free-web-hosts.php

**Comment by povrazor** [comment]
Good good, I like how you updated the lists to basically say what's supported. And the new blurb under free hosting is good.

I was going to recommend ButBucket earlier (for releases), but when I checked it, Bitbucket actually doesn't support releases. I would suggest double checking GitLab if they support it.

**Comment by zwrawr** [comment]
* Added Link to GitLab Pages
* Added Link to GitLab Tags *(releases)*
* Removed BitBuckit from game hosting section 

The Submitting to LudumDare section still needs to be written, but that'll have to wait till the game upload page is finalised

**Comment by povrazor** [comment]
Excellent. That's looking really good. And you're right, the submission section will have to be filled in. But still, that's a pretty good guide on what to expect.

Only thing I would is a couple extra details on source code hosting. For example:

* GitHub supports GIT, with an optional SVN interface to your GIT repo (word this better, haha)
* BitBucket supports both GIT and Mercurial

I thought about adding a Subversion host, but I really can't recommend sourceforge in good conscience. Google Code used to be my goto, but that's dead now. Assembla is what I used for a project some time ago, but I'm not sure they support open source (would have to check).

**Comment by zwrawr** [comment]
* Mentioned that GitHub hosts Git repos with support for svn clients
* Mentioned that GitLab hosts Git repos with support for svn clients
* Mentioned that BitBucket hosts Git and Mercurial repos *(didn't find any mentions of svn)*
* Slight changes to Submitting section.

**Comment by povrazor** [comment]
That's good. I think you've covered the bases well.

**Comment by povrazor** [comment]
Okay, I've posted the current version here:

https://ldjam.com/events/ludum-dare/hosting-guide

I'm going to see if I can quickly fix the anchor linking problem. I'll probably mean changing the links to `#l/whatever-its-called`, which isn't necessarily github compatible, but ah well. It's too useful a navigation feature.

**Comment by rblopes** [comment]
Just a heads up: On GitHub, one alternative and quicker way to host a game, especially for HTML5 games, is to enable GitHub Pages right in the repository. [This article from last year](https://github.com/blog/2228-simpler-github-pages-publishing) explains how.
