### ISSUE TITLE
@ldreleases policies and automation

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#551]
So a bit of a milestone today: Our Steam Curator now has over 50 games.

http://store.steampowered.com/curator/537829-Ludum-Dare/

I'd say we have a pretty good list, but it's true that it is easier today to get a game published on Steam than it was. In a few months, Valve will remove Greenlight and switch to a new system that should make things even easier. They will also be giving additional credibility and preference to Steam curators within Steam itself, and do nice things like create sub-lists (i.e. all games from LD 35 or such).

Ludum Dare's Steam Curator is informational. It's always been about sharing all Ludum Dare games on Steam, providing that community a reference of games that came out of our event. I'm aware that Steam Curators currently have a limit of 200'ish games, but I'm hoping that changes. Depending on how Valve changes the publishing process, a Steam Curator that has all Ludum Dare games on it may not be viable anymore.

***

Paired with the Steam Curation list, I always tweet from the **ludumdare** twitter account whenever we add a game to the list. This seems to be a thing some people like, and I often get requests to tweet about Greenlight campaigns, games released for mobile, and such. The problem is that with many thousands of games coming out of every Ludum Dare event, I worry that we might overwhelm followers of the main twitter account.

I made an exception to the usual rule a few years ago: I started tweeting Console game releases. There's no master list (NB: I need to reach out to Sony again), just a personal policy of sharing games that show up on PlayStation, Xbox, and Nintendo (after all, I come from a console development background). It hasn't happened yet, but I would like to see this extended to small-run releases for retro game systems (C64, etc).

Unfortunately, this exception of mine isn't fair to mobile games. Here's one I stumbled across:

https://www.youtube.com/watch?v=82g_MFiGQdY

And another from a dev that reached out to me today.

https://www.youtube.com/watch?v=xRblNIzu3BA

There's no question that the quality of Mobile games is on par with what gets released on Steam. It's true not every game is, but it's crappy that we've been ignoring them.

***

So, the point of this issue is that the policy needs to change.

The other key issue is that **this is work**. As an example, it took me over an hour to add and tweet 4 games recently released on Steam. I've started exporting the game trailer people are posting on Steam, plus writing the tweet takes time. Plus having to dig up the e-mail, the posts, and whatnot to find the games that are on Steam can be a bit of a chore.

So what I'm proposing is that featuring and curation needs to be part of the website in some way. But due to the quantity of games that should be considered, and not wanting to overwhelm followers of the **ludumdare** twitter account, the general policy of featured games should perhaps change.

**Comment by povrazor** [comment]
## What I'm considering
Obviously we need to open this up to more than just Steam and Console games. Unfortunately that means the number of games will be much higher, and that's not necessarily going to make people that follow the **ludumdare** twitter account happy.

So I'm thinking about creating a 2nd Twitter account for Ludum Dare Releases. This is a robot, like Steam seems to have. On the website itself we add some method of nominating your game for featuring by adding assets. i.e.

* a game page
* a trailer (mp4 file)
* a link to a store
* linkage to an original ludum dare game

Unfortunately I am thinking there needs to be some sort of approval process here. Something very loose, just to sanity check it using real humans. This is something that should probably be given to proven users, and like most things, allow for many new users to cycle in to this role automatically (i.e. karma based).

This does mean moving all game featuring to a separate Twitter account. That twitter account unfortunately will not have 50k followers, like the main Ludum Dare account has. But this way we can have an automated stream of new releases.

What changes is that the main **ludumdare** account now retweets this account, and that's the new policy. It should allow MP4 playback, and pretty-much every other twitter feature to work correctly. But it means that Tweets from **ludumdare** itself are more event/site focused.

Over time the releases account will grow a following, especially since **ludumdare** is retweeting them.

The elephant in the room though is that the retweeting still requires a human (me) to do it. That also means it's not very automatable, but it does mean I am in control of when the tweets happen.

If internally the people sanity checking nominations see something they like, it would be helpful if they could make a recommendation. This gets added to a list I see. That gives me the option of retweeting it now, or like it was done with Ludum Dare 38, queuing them up so we can make the weeks leading up to the Ludum Dare event more interesting, with content to share.

**Comment by povrazor** [comment]
## The other option
Just for completeness, another option I was considering was setting up an automation that tweeted a brand new released Ludum Dare game every day. But as I mentioned earlier, with Steam potentially opening up more, and being inclusive of mobile, the backlog might get out of hand fast.

**Comment by povrazor** [comment]
One last note: Keeping the number of posts-per-day by the the releases account to a minimum is a good idea. Though I do it myself, too many tweets in a row is actually kinda annoying. Spacing them out isn't so bad though.

**Comment by povrazor** [comment]
I've set up a twitter account.

https://twitter.com/ldreleases

Currently (and for a while) I'll be editing it by hand. I've re-posted the announcements from yesterday and today, and will start using it tomorrow for new releases (I have 2 more Steam games lined up).

**Comment by povrazor** [comment]
TODO: The Twitter Avatar for the releases account should be a box-art version of Ludum Dare.

Something like this...

![castlevania1987_zps6ecece1a](https://cloud.githubusercontent.com/assets/1570313/24824672/c8575576-1bdd-11e7-89a3-576d96dc1f92.png)

...keeping in mind that it needs to fit in a square, and is going to be tiny.

**Comment by mikekasprzak** [comment]
Renamed this issue. It now tracks progress on automating the @LDReleases twitter account

**Comment by mikekasprzak** [comment]
This discussion has moved here: https://github.com/LudumDare/ludumdare.com/discussions/15
