### ISSUE TITLE
[WriteMe] Judging Guide

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#887]
A lot of people seem to have a lot of questions about how the judging works, so there is probably a need for an FAQ style article on it.

Someone should write this as a gist which can be copied over to the site as an article.

## Guide should address
*
    > **timeracers (@timeracers)**
       I can’t find guidelines anywhere for how to rate Ludum Dare entries. Should we give an average of 3 stars? Does no sound mean the audio category should be rated 1? Questions like these should be answered somewhere.  

*
    > **Martin Zackrisson (@local-minimum)**
        I have question / suggestion about the game page. To me it isn't 100% clear if "your votes so far" is votes on my game vs votes cast by our team on other games. I'm leaning towards the first interpretation, but maybe rephrasing it somewhat?

    For reference the rating numbers displayed on **your game's** page is the number of ratings **your game** has received.

* **Why are some categories optional?**

* **When does voting start and finish. i.e. how long does voting last?**
   Normally 3 weeks (or two weeks?)

* **What is coolness, and how do i get it, and why is it so important?**
   It's a measure of how much your game deserves to get more votes. If you've been rating/reviewing lots of games and your game hasn't got many ratings yet then you'll be very cool. But if your game has lots of ratings and you haven't been rating/reviewing people then your not cool.

* **Can everyone is a team vote, does everyone coolness count?**
    Yes and Yes.

* **Can i vote if i didn't make an game?**
   Not currently, only participants can vote.

* **How are final results ranked / what categories?**

* **Does coolness effect my final rank?**
   Not directly but It does effect how many people vote for you and you need 20 votes to be ranked.

**Comment by local-minimum** [comment]
**Why are some categories optional?**

If you used audio that was not yours or not made during the weekend, as an example, you should opt-out of the `audio` category. This can of course become a bit hard where the line should be drawn. If you've added a ton of cool sound effects and worked on the mixing but used a public domain music track because you were out of time then it could be valid to keep audio-judging while making it very clear for everyone that they should not judge the music.

The same goes for graphics. And there's a general guideline about transformative work over [here].

Other reasons for opting out of categories may be:
* You feel like the category doesn't apply to your game. E.g. you made a pure text game and there's really no `graphics`.
* You don't want to be judged on that category

**Comment by local-minimum** [comment]
**How should I rate games?**
This really is entirely up to you, but in general vote fairly. And this is perhaps a lot harder than it sounds, because if your really didn't enjoy a game because the controls were horrible and you couldn't figure out what to do, it could still have awesome graphics. You could also consider how you would feel about getting ratings much lower than three stars average, but however you make your voting-system is up to you. It is up the the person making the game to play enough other games that all the voting variation on theirs balances out.

If a game has as the most common example, **no sound**, it shouldn't be given a grade. It could be commented in a kind manner to the maker that you didn't hear any sound and hope that was not a bug and if there actually wasn't any, perhaps they should opt-out of the category.

Some possible systems for voting (if you need help figuring out one yourself):
* Spread votes to average around 3 or perhaps 3.5 because it feels nicer to be kind.
* Set names for the different stars like for example 1=Offensive 2=Bad 3=Good 4=Very good 5=I can't believe they made this they are insanely talented.

**Comment by Bobsleigh** [comment]
It's important to mention the purpose of coolness, that is people with the most coolness get placed at the top of the search engine. So the way to get votes and comments on your game is to collect coolness by rating other game. I see a loooot of posts asking for votes and people seems desperate to get their game seen, which makes me think they don't know how to get it up the search engine. It is probably the most important point of the whole judging phase and should be highlighted.

**Comment by ajayyy** [comment]
However, some of these desperate people do actually have a decently high coolness, but a lot of people have waited until this weekend to start getting they're coolness, so there seems to be a lot of competition (look at the coolness of the top people, at least on feedback friends)

**Comment by local-minimum** [comment]
**Can I cheat the system?**
Ludum Dare is a community and a sure way to not make friends is to spam the site with `Cool game. Rate mine [link]`. It also steals time from Mike and others to deal with you.

One of the best ways to make sure you also get feedback is to take a moment to write something constructive about the game you just rated.  It is quite common on the site that people make sure to rate back and comment back on everyone that commented on theirs. So this will boost the number of votes you get in the long run.

The way the new algorithms work for which games end up at the top of the list, giving good feedback is really quite important.

If you are unlucky to have misunderstood how the voting period works and find yourself with less than 20 votes on your game and only a few days left, the best thing you can do is start playing other games with less than 20 votes. But be fair and rate them in a manner that you yourself would like people to have played and rated your game.

**Comment by mikekasprzak** [comment]
Moved to https://github.com/LudumDare/ludumdare.com/issues/4.
