### ISSUE TITLE
Python/Pygame users neglecting binaries (Py2EXE)

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#962]
There's a oddity in the python community: nobody shares binaries, just source/compiled bytecodes. This is perfectly fine as a python user, but not if you're everyone else. 

We used to have a community of users that would go out of their way to assist and help those that made Python entries by building Py2EXE binaries, but as things currently stand python users can't find each-other.

* https://ldjam.com/events/ludum-dare/38/random-invaders

Make sure those in the python family can find eachother again. With the new Karma for Feedback system, this is a perfect opportunity to earn it.

**Comment by Bobsleigh** [comment]
Python/pygame binaries are quite awkward to build/release when you're new. I posted a SO answer explaining how I do it with pyinstaller:

http://stackoverflow.com/questions/28033003/pyinstaller-with-pygame/36456473#36456473

On the old site I used the search bar to search for "python" or "pygame" to spread the news.

**Comment by povrazor** [comment]
Great. At the very least we need to facilitate this again.

Longer term though, I wonder: is there anything we can do to automate this? Like can we set up a generic online build-bot for spitting out a series of pygame binaries?

I realize Python has become rarer in the community, but I'm kinda intrigued by the idea of fixing this.

**Comment by Cerno-b** [comment]
There was a comment on the LD page that we should have developer guides on the site. I would agree to that. Maybe some form of Wiki-like page or a moderated page with comments where people can contribute and add common pitfalls, like how to properly deploy on itch, how to deal with porting Gamemaker games to Web, etc. A guide to publishing python games would just be another guide.

**Comment by local-minimum** [comment]
Now this wasn't the case with the one python game I played this time, but that game was 400mb download zipped (loads of art), so I don't really fancy the site anytime soon taking on building stuff, but I think it does applies to #965. We could, if there's a way to browse the content, check for executable.

**Comment by irskep** [comment]
A wiki with developer guides seems like a great idea. Really a game jam wiki in general. I would say it's out of scope for ldjam.com though.

**Comment by hugonun** [comment]
I used Pygame on my [ld43 game](https://ldjam.com/events/ludum-dare/43/the-kings-battle) and turned it into an exe file by using PyInstaller. It supports the newest Python and PyGame version and requires minimal changes to the PyInstaller config file (including icon file, manually tell where the non-Python required files are, disabling console). The great thing about it is that you can also "compile" for Linux and Mac.

I believe this can be automated, but PyInstaller has a history of "breaking" when a new Python version comes out, but fixes are often quick on the dev branch. For my game, I had to use the dev version because the stable version wasn't working.

We could automate this, but it might be better to also include a tutorial.

**Comment by mikekasprzak** [comment]
Yeah I'm less inclined to build-in this feature now, since Python use is
such a tiny part of our userbase. Definitely the way to go is to write a
tutorial.
