### ISSUE TITLE
I didn't finish but here's something else

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#963]
I've noticed a trend of games posted that read "I didn't finish, so here's something else"

* https://ldjam.com/events/ludum-dare/38/walking-bear-demo
* uhh, where did that link go?

I'm not entirely sure how to deal with these. Hopefully in the future these users just mark their game as unfinished.

**Comment by local-minimum** [comment]
I think before you didn't make your game-post until uploading and because this time you were encouraged to make them before you knew if you would finish, people felt confused about what to do then. So

a) this disappears if the initial version is always marked as `unfinished` unless people upload the game.
b) perhaps have `I give up` button on the draft game submission page to make in `unfinished +`
c) perhaps revert back to only make post when submitting game?

In any case I think it is important that the game doesn't show up on `/user/games` if unfinished because I guess people don't want them there.
